trigger:
  branches:
    include:
      - main

pool:
  name: 'Swimming Pool'

variables:
  solutionName: 'PracticeLearn1'
  solutionFolderPath: '$(Build.SourcesDirectory)/$(solutionName)/Unpacked/Managed'
  packedSolutionName: 'PracticeLearn1_1_0_1_0_managed.zip'
  packedSolutionPath: '$(Build.ArtifactStagingDirectory)/$(packedSolutionName)'
  environmentUrl: 'https://test-training-env.crm5.dynamics.com'
  serviceConnection: 'Service Connection Testing II Nhan Le Chinh'

steps:
  - task: PowerPlatformToolInstaller@2
    displayName: 'Install Power Platform CLI tools'

  - task: PowerPlatformPackSolution@2
    displayName: 'Pack Solution (Managed)'
    inputs:
      SolutionSourceFolder: '$(solutionFolderPath)'
      SolutionOutputFile: '$(packedSolutionPath)'
      SolutionType: 'Managed'  # Change to 'Unmanaged' if needed
      Overwrite: true

  - task: PowerPlatformImportSolution@2
    displayName: 'Import Managed Solution'
    inputs:
      authenticationType: 'PowerPlatformSPN'
      PowerPlatformSPN: '$(serviceConnection)'
      SolutionInputFile: '$(packedSolutionPath)'
      Environment: '$(environmentUrl)'
      AsyncOperation: true
      MaxAsyncWaitTime: '60'
      OverwriteUnmanagedCustomizations: true
